### ISSUE TITLE
PDF export functionality

### ISSUE THREAD

**Issue by joe-watkins** [Intopia/developing-czi-v2#19]
1. We need to look into whether or not there is support for PDF export via Reveal.js.
2. We need to ensure the PDF files are accessible. Crossing fingers.

**Comment by joe-watkins** [comment]
@russmaxdesign We can actually export to PDF _out-of-the-box_ with Reveal.js All we have to do is add `?print-pdf` to the end of the URL and it converts it to a print-ready version of the presentation / that session page. See attached. 

I don't believe the PDF is accessible though (quickly scanned and it's not tagged etc) so we'd have to outsource that prior to client delivery or just send along fine print that the web is the accessible version. 

I created a little screencast overview: https://www.screencast.com/t/s10ZUUQp

[Session 1_ The Accessibility tree and ARIA _ Developing for web accessibility.pdf](https://github.com/Intopia/developing-czi-v2/files/8421845/Session.1_.The.Accessibility.tree.and.ARIA._.Developing.for.web.accessibility.pdf)

**Comment by russmaxdesign** [comment]
This is incredible! I have sent a demo to a blind friend to review the accessibility, and will also purchase Adobe Acrobat to do some quick auto fixes, but this is a great short term solution.
